//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnRadio {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OnRadio.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе  .
        /// </summary>
        internal static string AboutBox_INFO {
            get {
                return ResourceManager.GetString("AboutBox_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        internal static string AboutBox_VER {
            get {
                return ResourceManager.GetString("AboutBox_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы точно хотите удалить из избранного  .
        /// </summary>
        internal static string button8Click {
            get {
                return ResourceManager.GetString("button8Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   Сообщение.
        /// </summary>
        internal static string button8Click2 {
            get {
                return ResourceManager.GetString("button8Click2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция:  .
        /// </summary>
        internal static string button8Click3 {
            get {
                return ResourceManager.GetString("button8Click3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   удалена из избранного! .
        /// </summary>
        internal static string button8Click4 {
            get {
                return ResourceManager.GetString("button8Click4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   Добавить  .
        /// </summary>
        internal static string button8Click5 {
            get {
                return ResourceManager.GetString("button8Click5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   в избранное? .
        /// </summary>
        internal static string button8Click6 {
            get {
                return ResourceManager.GetString("button8Click6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на добавлена в избранное!.
        /// </summary>
        internal static string button8Click7 {
            get {
                return ResourceManager.GetString("button8Click7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить в избранное.
        /// </summary>
        internal static string button8text {
            get {
                return ResourceManager.GetString("button8text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить из избранного.
        /// </summary>
        internal static string button8text2 {
            get {
                return ResourceManager.GetString("button8text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на     Все радиостанции.
        /// </summary>
        internal static string button9text {
            get {
                return ResourceManager.GetString("button9text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  В   избранное.
        /// </summary>
        internal static string button9text2 {
            get {
                return ResourceManager.GetString("button9text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего станций:  .
        /// </summary>
        internal static string count_str {
            get {
                return ResourceManager.GetString("count_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных создана.
        /// </summary>
        internal static string CreateBD {
            get {
                return ResourceManager.GetString("CreateBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на База данных отсутствует!.
        /// </summary>
        internal static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создайте новую базу данных..
        /// </summary>
        internal static string FileExists2 {
            get {
                return ResourceManager.GetString("FileExists2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить данные из буфера обмена.
        /// </summary>
        internal static string IDataO {
            get {
                return ResourceManager.GetString("IDataO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись идет.
        /// </summary>
        internal static string is_recorded {
            get {
                return ResourceManager.GetString("is_recorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть папку с файлом?.
        /// </summary>
        internal static string Open_folder {
            get {
                return ResourceManager.GetString("Open_folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удаление записи.
        /// </summary>
        internal static string picDel_C {
            get {
                return ResourceManager.GetString("picDel_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Вы действительно хотите удалить запись? .
        /// </summary>
        internal static string picDel_C1 {
            get {
                return ResourceManager.GetString("picDel_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Радио станция:  .
        /// </summary>
        internal static string picDel_C2 {
            get {
                return ResourceManager.GetString("picDel_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись невозможно будет восстановить!.
        /// </summary>
        internal static string picDel_C3 {
            get {
                return ResourceManager.GetString("picDel_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось внести изменения .
        /// </summary>
        internal static string picDel_C4 {
            get {
                return ResourceManager.GetString("picDel_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись не изменена .
        /// </summary>
        internal static string picDel_C5 {
            get {
                return ResourceManager.GetString("picDel_C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Размер изображения не соответствует. .
        /// </summary>
        internal static string picFdialog_C {
            get {
                return ResourceManager.GetString("picFdialog_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   Необходимо 210 х 64 пикселя. .
        /// </summary>
        internal static string picFdialog_C1 {
            get {
                return ResourceManager.GetString("picFdialog_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Размер изображения: ширина =  .
        /// </summary>
        internal static string picFdialog_C2 {
            get {
                return ResourceManager.GetString("picFdialog_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  , высота =  .
        /// </summary>
        internal static string picFdialog_C3 {
            get {
                return ResourceManager.GetString("picFdialog_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  пикселя.  .
        /// </summary>
        internal static string picFdialog_C4 {
            get {
                return ResourceManager.GetString("picFdialog_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Выберете другое изображение?  .
        /// </summary>
        internal static string picFdialog_C5 {
            get {
                return ResourceManager.GetString("picFdialog_C5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Выбор логотипа  .
        /// </summary>
        internal static string picFdialog_C6 {
            get {
                return ResourceManager.GetString("picFdialog_C6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логотип не выбран.
        /// </summary>
        internal static string picFdialog_C7 {
            get {
                return ResourceManager.GetString("picFdialog_C7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось внести изменения .
        /// </summary>
        internal static string picFdialog_C8 {
            get {
                return ResourceManager.GetString("picFdialog_C8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование  записей.
        /// </summary>
        internal static string picSave_C {
            get {
                return ResourceManager.GetString("picSave_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить все поля .
        /// </summary>
        internal static string picSave_C1 {
            get {
                return ResourceManager.GetString("picSave_C1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы хотите изменить запись? .
        /// </summary>
        internal static string picSave_C2 {
            get {
                return ResourceManager.GetString("picSave_C2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   будет изменена на  .
        /// </summary>
        internal static string picSave_C3 {
            get {
                return ResourceManager.GetString("picSave_C3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  - изменена на  .
        /// </summary>
        internal static string picSave_C4 {
            get {
                return ResourceManager.GetString("picSave_C4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без звука.
        /// </summary>
        internal static string pictureOff {
            get {
                return ResourceManager.GetString("pictureOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Со звуком.
        /// </summary>
        internal static string pictureOn {
            get {
                return ResourceManager.GetString("pictureOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Я здесь, если ты передумаешь.
        /// </summary>
        internal static string RadioBTip {
            get {
                return ResourceManager.GetString("RadioBTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сейчас в эфире:.
        /// </summary>
        internal static string RadioBTip2 {
            get {
                return ResourceManager.GetString("RadioBTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись сохранена в: .
        /// </summary>
        internal static string Recording_saved {
            get {
                return ResourceManager.GetString("Recording_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приложение уже запущено  .
        /// </summary>
        internal static string RunOnly {
            get {
                return ResourceManager.GetString("RunOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   сохранена в базу данных..
        /// </summary>
        internal static string SaveImag {
            get {
                return ResourceManager.GetString("SaveImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Без сортировки.
        /// </summary>
        internal static string sortMenuOff {
            get {
                return ResourceManager.GetString("sortMenuOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сортировка  (от А до Я).
        /// </summary>
        internal static string sortMenuOn {
            get {
                return ResourceManager.GetString("sortMenuOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начать запись?.
        /// </summary>
        internal static string Start_record {
            get {
                return ResourceManager.GetString("Start_record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Остановить запись?.
        /// </summary>
        internal static string Stop_recording {
            get {
                return ResourceManager.GetString("Stop_recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OnRadio - удобная программа,                    чтобы слушать радио через интернет!.
        /// </summary>
        internal static string TextBoxDescript {
            get {
                return ResourceManager.GetString("TextBoxDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Воспроизведение.
        /// </summary>
        internal static string toolStripStatusLabeltext {
            get {
                return ResourceManager.GetString("toolStripStatusLabeltext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приостановлено.
        /// </summary>
        internal static string toolStripStatusLabeltext2 {
            get {
                return ResourceManager.GetString("toolStripStatusLabeltext2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет подключения к интернету!.
        /// </summary>
        internal static string toolStripStatusLabeltext3 {
            get {
                return ResourceManager.GetString("toolStripStatusLabeltext3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение. . . . . . . . . . ..
        /// </summary>
        internal static string toolStripStatusLabeltext4 {
            get {
                return ResourceManager.GetString("toolStripStatusLabeltext4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервер выключен или не отвечает!.
        /// </summary>
        internal static string toolStripStatusLabeltext5 {
            get {
                return ResourceManager.GetString("toolStripStatusLabeltext5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cкорость потока:.
        /// </summary>
        internal static string toolStripStatusLabeltext6 {
            get {
                return ResourceManager.GetString("toolStripStatusLabeltext6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на   кбит/с.
        /// </summary>
        internal static string toolStripStatusLabeltext7 {
            get {
                return ResourceManager.GetString("toolStripStatusLabeltext7", resourceCulture);
            }
        }
    }
}
